/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 station-train.glb --transform 
Files: station-train.glb [36.3MB] > C:\Users\ELOHOME LTD\WebstormProjects\train-model\src\models\station-train-transformed.glb [2.7MB] (93%)
Author: Thomas Nguyen (https://sketchfab.com/thomasnguyen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nazo-no-eki-mystery-station-6cbd6ce6354f44a4b6517e8176d8741b
Title: Nazo no eki (Mystery Station)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function StationTrain(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/station-train-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.016}>
          <group name="Water" position={[0, -0.625, 0]} scale={[120, 3, 100]}>
            <mesh name="Water_Water_MAT1_0" geometry={nodes.Water_Water_MAT1_0.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Water_Water_MAT_0" geometry={nodes.Water_Water_MAT_0.geometry} material={materials.PaletteMaterial002} />
          </group>
          <group name="Train" position={[7.5, 0, 0]}>
            <group name="Train_Start">
              <group name="Train_Body" position={[0, 5, 0]} scale={[14, 8, 6]}>
                <mesh name="Train_Body_Person_MAT_0" geometry={nodes.Train_Body_Person_MAT_0.geometry} material={materials.PaletteMaterial003} />
                <mesh name="Train_Body_Glass_MAT_0" geometry={nodes.Train_Body_Glass_MAT_0.geometry} material={materials.PaletteMaterial004} />
                <mesh name="Train_Body_White_0" geometry={nodes.Train_Body_White_0.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Message" position={[6.767, 7.944, 0]} scale={[0.267, 0.724, 2.171]}>
                <mesh name="Message_Metal_MAT_0" geometry={nodes.Message_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
                <mesh name="Message_Pristine_MAT_0" geometry={nodes.Message_Pristine_MAT_0.geometry} material={materials.Pristine_MAT} />
              </group>
              <group name="Headlight2" position={[7.1, 2.72, 2]} rotation={[0, 0, Math.PI / 2]} scale={0.5}>
                <mesh name="Headlight2_Ground_MAT_0" geometry={nodes.Headlight2_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
                <mesh name="Headlight2_Glass_MAT_0" geometry={nodes.Headlight2_Glass_MAT_0.geometry} material={materials.PaletteMaterial004} />
              </group>
              <group name="Headlight1" position={[7.1, 2.72, -2]} rotation={[0, 0, Math.PI / 2]} scale={0.5}>
                <mesh name="Headlight1_Ground_MAT_0" geometry={nodes.Headlight1_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
                <mesh name="Headlight1_Glass_MAT_0" geometry={nodes.Headlight1_Glass_MAT_0.geometry} material={materials.PaletteMaterial004} />
              </group>
              <group name="Sign" position={[6.457, 7.944, 0]} scale={[0.65, 1, 3]}>
                <mesh name="Sign_Ground_MAT_0" geometry={nodes.Sign_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Duct" position={[-3.342, 9.4, 0]} scale={[4.572, 0.929, 3.158]}>
                <mesh name="Duct_Ground_MAT_0" geometry={nodes.Duct_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Steam_Engine" position={[2.49, 9.4, 0]} scale={[1, 0.5, 1]}>
                <mesh name="Steam_Engine_Ground_MAT_0" geometry={nodes.Steam_Engine_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Window_Bar" position={[0, 7.363, 0]} scale={[3.31, 0.237, 5.783]}>
                <mesh name="Window_Bar_Ground_MAT_0" geometry={nodes.Window_Bar_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Handle1" position={[-1.663, 5, 0]} scale={[3.31, 0.237, 5.783]}>
                <mesh name="Handle1_Ground_MAT_0" geometry={nodes.Handle1_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Handle2" position={[-2.209, 5, 0.508]} scale={[3.31, 0.237, 4.869]}>
                <mesh name="Handle2_Ground_MAT_0" geometry={nodes.Handle2_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Mirror" position={[7.182, 6.678, 2.85]} rotation={[-0.033, -0.207, 0.089]} scale={[0.438, 1.343, 0.723]}>
                <mesh name="Mirror_Ground_MAT_0" geometry={nodes.Mirror_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
                <mesh name="Mirror_Glass_MAT_0" geometry={nodes.Mirror_Glass_MAT_0.geometry} material={materials.PaletteMaterial004} />
              </group>
              <group name="Mirror_Handle_1" position={[7.407, 7.132, 2.901]} rotation={[0.01, -0.023, -0.079]} scale={[0.08, 0.5, 0.08]}>
                <mesh name="Mirror_Handle_1_Ground_MAT_0" geometry={nodes.Mirror_Handle_1_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Mirror_Handle_2" position={[6.869, 7.552, 2.743]} rotation={[-0.055, -0.266, 1.552]} scale={[0.08, 0.62, 0.08]}>
                <mesh name="Mirror_Handle_2_Ground_MAT_0" geometry={nodes.Mirror_Handle_2_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Cart_Top1" position={[-0.07, 9.25, 0]} scale={[13.5, 0.4, 6]}>
                <mesh name="Cart_Top1_White_0" geometry={nodes.Cart_Top1_White_0.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Wheels">
                <group name="pCylinder47" position={[-5, 1, -2]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 0.2, 1]}>
                  <mesh name="pCylinder47_Ground_MAT_0" geometry={nodes.pCylinder47_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="pCylinder45" position={[3, 1, -2]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 0.2, 1]}>
                  <mesh name="pCylinder45_Ground_MAT_0" geometry={nodes.pCylinder45_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="pCylinder44" position={[5, 1, -2]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 0.2, 1]}>
                  <mesh name="pCylinder44_Ground_MAT_0" geometry={nodes.pCylinder44_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="pCylinder51" position={[5, 1, 2]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.2, 1]}>
                  <mesh name="pCylinder51_Ground_MAT_0" geometry={nodes.pCylinder51_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="pCylinder50" position={[3, 1, 2]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.2, 1]}>
                  <mesh name="pCylinder50_Ground_MAT_0" geometry={nodes.pCylinder50_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="pCylinder49" position={[-3, 1, 2]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.2, 1]}>
                  <mesh name="pCylinder49_Ground_MAT_0" geometry={nodes.pCylinder49_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="pCylinder48" position={[-5, 1, 2]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.2, 1]}>
                  <mesh name="pCylinder48_Ground_MAT_0" geometry={nodes.pCylinder48_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="pCylinder46" position={[-3, 1, -2]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 0.2, 1]}>
                  <mesh name="pCylinder46_Ground_MAT_0" geometry={nodes.pCylinder46_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
                </group>
              </group>
              <group name="Wheels_Support" position={[62, 0, 0]}>
                <group name="pCube22" position={[-66, 0.679, 2.522]} scale={[2.892, 0.186, 0.136]}>
                  <mesh name="pCube22_Metal_MAT_0" geometry={nodes.pCube22_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube23" position={[-58, 0.679, 2.522]} scale={[2.892, 0.186, 0.136]}>
                  <mesh name="pCube23_Metal_MAT_0" geometry={nodes.pCube23_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube24" position={[-62, 1.647, 2.522]} scale={[4.287, 0.186, 0.136]}>
                  <mesh name="pCube24_Metal_MAT_0" geometry={nodes.pCube24_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube25" position={[-67.354, 1.022, 2.522]} scale={[0.181, 0.676, 0.136]}>
                  <mesh name="pCube25_Metal_MAT_0" geometry={nodes.pCube25_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube26" position={[-64.645, 1.022, 2.522]} scale={[0.181, 0.676, 0.136]}>
                  <mesh name="pCube26_Metal_MAT_0" geometry={nodes.pCube26_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube27" position={[-59.357, 1.022, 2.522]} scale={[0.181, 0.676, 0.136]}>
                  <mesh name="pCube27_Metal_MAT_0" geometry={nodes.pCube27_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube28" position={[-56.643, 1.022, 2.522]} scale={[0.181, 0.676, 0.136]}>
                  <mesh name="pCube28_Metal_MAT_0" geometry={nodes.pCube28_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube29" position={[-56.643, 1.022, -2.493]} scale={[0.181, 0.676, 0.136]}>
                  <mesh name="pCube29_Metal_MAT_0" geometry={nodes.pCube29_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube30" position={[-58, 0.679, -2.493]} scale={[2.892, 0.186, 0.136]}>
                  <mesh name="pCube30_Metal_MAT_0" geometry={nodes.pCube30_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube31" position={[-59.357, 1.022, -2.493]} scale={[0.181, 0.676, 0.136]}>
                  <mesh name="pCube31_Metal_MAT_0" geometry={nodes.pCube31_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube32" position={[-62, 1.647, -2.493]} scale={[4.287, 0.186, 0.136]}>
                  <mesh name="pCube32_Metal_MAT_0" geometry={nodes.pCube32_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube33" position={[-64.645, 1.022, -2.493]} scale={[0.181, 0.676, 0.136]}>
                  <mesh name="pCube33_Metal_MAT_0" geometry={nodes.pCube33_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube34" position={[-66, 0.679, -2.493]} scale={[2.892, 0.186, 0.136]}>
                  <mesh name="pCube34_Metal_MAT_0" geometry={nodes.pCube34_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube35" position={[-67.354, 1.022, -2.493]} scale={[0.181, 0.676, 0.136]}>
                  <mesh name="pCube35_Metal_MAT_0" geometry={nodes.pCube35_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
                </group>
              </group>
              <group name="BackDoor_Bar" position={[-6.8, 5.443, 0]} scale={[0.2, 0.237, 2.1]}>
                <mesh name="BackDoor_Bar_Ground_MAT_0" geometry={nodes.BackDoor_Bar_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
              </group>
            </group>
            <group name="Train_Cart1">
              <group name="Cart" position={[-15, 5, 0]} scale={[14, 8, 6]}>
                <mesh name="Cart_Person_MAT_0" geometry={nodes.Cart_Person_MAT_0.geometry} material={materials.PaletteMaterial003} />
                <mesh name="Cart_Glass_MAT_0" geometry={nodes.Cart_Glass_MAT_0.geometry} material={materials.PaletteMaterial004} />
                <mesh name="Cart_White_0" geometry={nodes.Cart_White_0.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Cart_Top2" position={[-15.07, 9.1, 0]} scale={[14, 0.4, 6]}>
                <mesh name="Cart_Top2_White_0" geometry={nodes.Cart_Top2_White_0.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Handles1" position={[-16.913, 4.966, 0]} scale={[3.836, 0.237, 5.783]}>
                <mesh name="Handles1_Ground_MAT_0" geometry={nodes.Handles1_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Window_Bar_1" position={[-14.994, 7.363, 0]} scale={[3.836, 0.237, 5.783]}>
                <mesh name="Window_Bar_Ground_MAT_0_1" geometry={nodes.Window_Bar_Ground_MAT_0_1.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Duct_1" position={[-15, 9.3, 0]} scale={[4.572, 0.929, 3.158]}>
                <mesh name="Duct_Ground_MAT_0_1" geometry={nodes.Duct_Ground_MAT_0_1.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Handles2" position={[-13.02, 4.966, 0]} scale={[3.836, 0.237, 5.783]}>
                <mesh name="Handles2_Ground_MAT_0" geometry={nodes.Handles2_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Wheels1" position={[-15, 0, 0]}>
                <group name="pCylinder47_1" position={[-5, 1, -2]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 0.2, 1]}>
                  <mesh name="pCylinder47_Ground_MAT_0_1" geometry={nodes.pCylinder47_Ground_MAT_0_1.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="pCylinder45_1" position={[3, 1, -2]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 0.2, 1]}>
                  <mesh name="pCylinder45_Ground_MAT_0_1" geometry={nodes.pCylinder45_Ground_MAT_0_1.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="pCylinder44_1" position={[5, 1, -2]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 0.2, 1]}>
                  <mesh name="pCylinder44_Ground_MAT_0_1" geometry={nodes.pCylinder44_Ground_MAT_0_1.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="pCylinder51_1" position={[5, 1, 2]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.2, 1]}>
                  <mesh name="pCylinder51_Ground_MAT_0_1" geometry={nodes.pCylinder51_Ground_MAT_0_1.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="pCylinder50_1" position={[3, 1, 2]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.2, 1]}>
                  <mesh name="pCylinder50_Ground_MAT_0_1" geometry={nodes.pCylinder50_Ground_MAT_0_1.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="pCylinder49_1" position={[-3, 1, 2]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.2, 1]}>
                  <mesh name="pCylinder49_Ground_MAT_0_1" geometry={nodes.pCylinder49_Ground_MAT_0_1.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="pCylinder48_1" position={[-5, 1, 2]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.2, 1]}>
                  <mesh name="pCylinder48_Ground_MAT_0_1" geometry={nodes.pCylinder48_Ground_MAT_0_1.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="pCylinder46_1" position={[-3, 1, -2]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 0.2, 1]}>
                  <mesh name="pCylinder46_Ground_MAT_0_1" geometry={nodes.pCylinder46_Ground_MAT_0_1.geometry} material={materials.PaletteMaterial001} />
                </group>
              </group>
              <group name="Wheels_Support1" position={[47, 0, 0]}>
                <group name="pCube22_1" position={[-66, 0.679, 2.522]} scale={[2.892, 0.186, 0.136]}>
                  <mesh name="pCube22_Metal_MAT_0_1" geometry={nodes.pCube22_Metal_MAT_0_1.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube23_1" position={[-58, 0.679, 2.522]} scale={[2.892, 0.186, 0.136]}>
                  <mesh name="pCube23_Metal_MAT_0_1" geometry={nodes.pCube23_Metal_MAT_0_1.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube24_1" position={[-62, 1.647, 2.522]} scale={[4.287, 0.186, 0.136]}>
                  <mesh name="pCube24_Metal_MAT_0_1" geometry={nodes.pCube24_Metal_MAT_0_1.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube25_1" position={[-67.354, 1.022, 2.522]} scale={[0.181, 0.676, 0.136]}>
                  <mesh name="pCube25_Metal_MAT_0_1" geometry={nodes.pCube25_Metal_MAT_0_1.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube26_1" position={[-64.645, 1.022, 2.522]} scale={[0.181, 0.676, 0.136]}>
                  <mesh name="pCube26_Metal_MAT_0_1" geometry={nodes.pCube26_Metal_MAT_0_1.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube27_1" position={[-59.357, 1.022, 2.522]} scale={[0.181, 0.676, 0.136]}>
                  <mesh name="pCube27_Metal_MAT_0_1" geometry={nodes.pCube27_Metal_MAT_0_1.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube28_1" position={[-56.643, 1.022, 2.522]} scale={[0.181, 0.676, 0.136]}>
                  <mesh name="pCube28_Metal_MAT_0_1" geometry={nodes.pCube28_Metal_MAT_0_1.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube29_1" position={[-56.643, 1.022, -2.493]} scale={[0.181, 0.676, 0.136]}>
                  <mesh name="pCube29_Metal_MAT_0_1" geometry={nodes.pCube29_Metal_MAT_0_1.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube30_1" position={[-58, 0.679, -2.493]} scale={[2.892, 0.186, 0.136]}>
                  <mesh name="pCube30_Metal_MAT_0_1" geometry={nodes.pCube30_Metal_MAT_0_1.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube31_1" position={[-59.357, 1.022, -2.493]} scale={[0.181, 0.676, 0.136]}>
                  <mesh name="pCube31_Metal_MAT_0_1" geometry={nodes.pCube31_Metal_MAT_0_1.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube32_1" position={[-62, 1.647, -2.493]} scale={[4.287, 0.186, 0.136]}>
                  <mesh name="pCube32_Metal_MAT_0_1" geometry={nodes.pCube32_Metal_MAT_0_1.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube33_1" position={[-64.645, 1.022, -2.493]} scale={[0.181, 0.676, 0.136]}>
                  <mesh name="pCube33_Metal_MAT_0_1" geometry={nodes.pCube33_Metal_MAT_0_1.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube34_1" position={[-66, 0.679, -2.493]} scale={[2.892, 0.186, 0.136]}>
                  <mesh name="pCube34_Metal_MAT_0_1" geometry={nodes.pCube34_Metal_MAT_0_1.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube35_1" position={[-67.354, 1.022, -2.493]} scale={[0.181, 0.676, 0.136]}>
                  <mesh name="pCube35_Metal_MAT_0_1" geometry={nodes.pCube35_Metal_MAT_0_1.geometry} material={materials.PaletteMaterial003} />
                </group>
              </group>
              <group name="FrontDoor_Bar" position={[-8.2, 5, 0]} scale={[0.2, 0.237, 2.1]}>
                <mesh name="FrontDoor_Bar_Ground_MAT_0" geometry={nodes.FrontDoor_Bar_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="BackDoor_Bar_1" position={[-21.8, 5, 0]} scale={[0.2, 0.237, 2.1]}>
                <mesh name="BackDoor_Bar_Ground_MAT_0_1" geometry={nodes.BackDoor_Bar_Ground_MAT_0_1.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Connector1" position={[34.93, 0, 0]}>
                <group name="Connector" position={[-42.45, 1.98, 0]} scale={[0.4, 0.15, 0.4]}>
                  <mesh name="Connector_Metal_MAT_0" geometry={nodes.Connector_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="Connector1_1" position={[-42.05, 2, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[1.5, 0.2, 0.6]}>
                  <mesh name="Connector1_Ground_MAT_0" geometry={nodes.Connector1_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="Connector2_1" position={[-42.85, 2, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[1.5, 0.2, 0.6]}>
                  <mesh name="Connector2_Ground_MAT_0" geometry={nodes.Connector2_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
                </group>
              </group>
            </group>
            <group name="Train_Cart2" position={[-15, 0, 0]}>
              <group name="Cart_1" position={[-15, 5, 0]} scale={[14, 8, 6]}>
                <mesh name="Cart_Glass_MAT_0_1" geometry={nodes.Cart_Glass_MAT_0_1.geometry} material={materials.PaletteMaterial004} />
                <mesh name="Cart_White_0_1" geometry={nodes.Cart_White_0_1.geometry} material={materials.PaletteMaterial001} />
                <mesh name="Cart_Person_MAT_0_1" geometry={nodes.Cart_Person_MAT_0_1.geometry} material={materials.PaletteMaterial003} />
              </group>
              <group name="Cart_Top2_1" position={[-15.07, 9.1, 0]} scale={[14, 0.4, 6]}>
                <mesh name="Cart_Top2_White_0_1" geometry={nodes.Cart_Top2_White_0_1.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Handles1_1" position={[-16.913, 4.966, 0]} scale={[3.836, 0.237, 5.783]}>
                <mesh name="Handles1_Ground_MAT_0_1" geometry={nodes.Handles1_Ground_MAT_0_1.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Window_Bar_2" position={[-14.994, 7.363, 0]} scale={[3.836, 0.237, 5.783]}>
                <mesh name="Window_Bar_Ground_MAT_0_2" geometry={nodes.Window_Bar_Ground_MAT_0_2.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Duct_2" position={[-15, 9.3, 0]} scale={[4.572, 0.929, 3.158]}>
                <mesh name="Duct_Ground_MAT_0_2" geometry={nodes.Duct_Ground_MAT_0_2.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Handles2_1" position={[-13.02, 4.966, 0]} scale={[3.836, 0.237, 5.783]}>
                <mesh name="Handles2_Ground_MAT_0_1" geometry={nodes.Handles2_Ground_MAT_0_1.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Wheels1_1" position={[-15, 0, 0]}>
                <group name="pCylinder47_2" position={[-5, 1, -2]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 0.2, 1]}>
                  <mesh name="pCylinder47_Ground_MAT_0_2" geometry={nodes.pCylinder47_Ground_MAT_0_2.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="pCylinder45_2" position={[3, 1, -2]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 0.2, 1]}>
                  <mesh name="pCylinder45_Ground_MAT_0_2" geometry={nodes.pCylinder45_Ground_MAT_0_2.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="pCylinder44_2" position={[5, 1, -2]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 0.2, 1]}>
                  <mesh name="pCylinder44_Ground_MAT_0_2" geometry={nodes.pCylinder44_Ground_MAT_0_2.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="pCylinder51_2" position={[5, 1, 2]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.2, 1]}>
                  <mesh name="pCylinder51_Ground_MAT_0_2" geometry={nodes.pCylinder51_Ground_MAT_0_2.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="pCylinder50_2" position={[3, 1, 2]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.2, 1]}>
                  <mesh name="pCylinder50_Ground_MAT_0_2" geometry={nodes.pCylinder50_Ground_MAT_0_2.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="pCylinder49_2" position={[-3, 1, 2]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.2, 1]}>
                  <mesh name="pCylinder49_Ground_MAT_0_2" geometry={nodes.pCylinder49_Ground_MAT_0_2.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="pCylinder48_2" position={[-5, 1, 2]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.2, 1]}>
                  <mesh name="pCylinder48_Ground_MAT_0_2" geometry={nodes.pCylinder48_Ground_MAT_0_2.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="pCylinder46_2" position={[-3, 1, -2]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 0.2, 1]}>
                  <mesh name="pCylinder46_Ground_MAT_0_2" geometry={nodes.pCylinder46_Ground_MAT_0_2.geometry} material={materials.PaletteMaterial001} />
                </group>
              </group>
              <group name="Wheels_Support1_1" position={[47, 0, 0]}>
                <group name="pCube22_2" position={[-66, 0.679, 2.522]} scale={[2.892, 0.186, 0.136]}>
                  <mesh name="pCube22_Metal_MAT_0_2" geometry={nodes.pCube22_Metal_MAT_0_2.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube23_2" position={[-58, 0.679, 2.522]} scale={[2.892, 0.186, 0.136]}>
                  <mesh name="pCube23_Metal_MAT_0_2" geometry={nodes.pCube23_Metal_MAT_0_2.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube24_2" position={[-62, 1.647, 2.522]} scale={[4.287, 0.186, 0.136]}>
                  <mesh name="pCube24_Metal_MAT_0_2" geometry={nodes.pCube24_Metal_MAT_0_2.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube25_2" position={[-67.354, 1.022, 2.522]} scale={[0.181, 0.676, 0.136]}>
                  <mesh name="pCube25_Metal_MAT_0_2" geometry={nodes.pCube25_Metal_MAT_0_2.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube26_2" position={[-64.645, 1.022, 2.522]} scale={[0.181, 0.676, 0.136]}>
                  <mesh name="pCube26_Metal_MAT_0_2" geometry={nodes.pCube26_Metal_MAT_0_2.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube27_2" position={[-59.357, 1.022, 2.522]} scale={[0.181, 0.676, 0.136]}>
                  <mesh name="pCube27_Metal_MAT_0_2" geometry={nodes.pCube27_Metal_MAT_0_2.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube28_2" position={[-56.643, 1.022, 2.522]} scale={[0.181, 0.676, 0.136]}>
                  <mesh name="pCube28_Metal_MAT_0_2" geometry={nodes.pCube28_Metal_MAT_0_2.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube29_2" position={[-56.643, 1.022, -2.493]} scale={[0.181, 0.676, 0.136]}>
                  <mesh name="pCube29_Metal_MAT_0_2" geometry={nodes.pCube29_Metal_MAT_0_2.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube30_2" position={[-58, 0.679, -2.493]} scale={[2.892, 0.186, 0.136]}>
                  <mesh name="pCube30_Metal_MAT_0_2" geometry={nodes.pCube30_Metal_MAT_0_2.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube31_2" position={[-59.357, 1.022, -2.493]} scale={[0.181, 0.676, 0.136]}>
                  <mesh name="pCube31_Metal_MAT_0_2" geometry={nodes.pCube31_Metal_MAT_0_2.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube32_2" position={[-62, 1.647, -2.493]} scale={[4.287, 0.186, 0.136]}>
                  <mesh name="pCube32_Metal_MAT_0_2" geometry={nodes.pCube32_Metal_MAT_0_2.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube33_2" position={[-64.645, 1.022, -2.493]} scale={[0.181, 0.676, 0.136]}>
                  <mesh name="pCube33_Metal_MAT_0_2" geometry={nodes.pCube33_Metal_MAT_0_2.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube34_2" position={[-66, 0.679, -2.493]} scale={[2.892, 0.186, 0.136]}>
                  <mesh name="pCube34_Metal_MAT_0_2" geometry={nodes.pCube34_Metal_MAT_0_2.geometry} material={materials.PaletteMaterial003} />
                </group>
                <group name="pCube35_2" position={[-67.354, 1.022, -2.493]} scale={[0.181, 0.676, 0.136]}>
                  <mesh name="pCube35_Metal_MAT_0_2" geometry={nodes.pCube35_Metal_MAT_0_2.geometry} material={materials.PaletteMaterial003} />
                </group>
              </group>
              <group name="FrontDoor_Bar_1" position={[-8.2, 5, 0]} scale={[0.2, 0.237, 2.1]}>
                <mesh name="FrontDoor_Bar_Ground_MAT_0_1" geometry={nodes.FrontDoor_Bar_Ground_MAT_0_1.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="BackDoor_Bar_2" position={[-21.8, 5, 0]} scale={[0.2, 0.237, 2.1]}>
                <mesh name="BackDoor_Bar_Ground_MAT_0_2" geometry={nodes.BackDoor_Bar_Ground_MAT_0_2.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Connector2" position={[49.95, 0, 0]}>
                <group name="Connector5" position={[-57.85, 2, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[1.5, 0.2, 0.6]}>
                  <mesh name="Connector5_Ground_MAT_0" geometry={nodes.Connector5_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="Connector4" position={[-57.05, 2, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[1.5, 0.2, 0.6]}>
                  <mesh name="Connector4_Ground_MAT_0" geometry={nodes.Connector4_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="Connector3" position={[-57.45, 1.98, 0]} scale={[0.4, 0.15, 0.4]}>
                  <mesh name="Connector3_Metal_MAT_0" geometry={nodes.Connector3_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
                </group>
              </group>
            </group>
            <group name="TrainBack" position={[7.609, 0, 0]}>
              <group name="TrainBack_Platform">
                <mesh name="TrainBack_Platform_Ground_MAT_0" geometry={nodes.TrainBack_Platform_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="TrainBack_Bars">
                <group name="polySurface1" position={[0, 0, 0.085]}>
                  <mesh name="polySurface1_Ground_MAT_0" geometry={nodes.polySurface1_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="polySurface3" position={[-0.352, -4.178, 0]} rotation={[0, 0, -0.087]}>
                  <mesh name="polySurface3_Ground_MAT_0" geometry={nodes.polySurface3_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="polySurface5" position={[0, 0, -0.005]}>
                  <mesh name="polySurface5_Ground_MAT_0" geometry={nodes.polySurface5_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="polySurface6" position={[1.191, 6.387, 0.916]} rotation={[0.13, 0.017, 0.13]}>
                  <mesh name="polySurface6_Ground_MAT_0" geometry={nodes.polySurface6_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
                </group>
                <group name="polySurface7" position={[1.191, 6.387, -0.916]} rotation={[-0.13, -0.017, 0.13]}>
                  <mesh name="polySurface7_Ground_MAT_0" geometry={nodes.polySurface7_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
                </group>
              </group>
              <group name="TrainBack_Railing">
                <mesh name="TrainBack_Railing_Ground_MAT_0" geometry={nodes.TrainBack_Railing_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="TrainBack_Top" position={[-45.609, 8.5, 0]} scale={[3, 0.4, 4.7]}>
                <mesh name="TrainBack_Top_Ground_MAT_0" geometry={nodes.TrainBack_Top_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
              </group>
            </group>
            <group name="Cone_Light4" position={[15.226, 2.725, 2]} rotation={[0, 0, Math.PI / 2]} scale={[1, 8, 1]}>
              <mesh name="Cone_Light4_HeadLight_0" geometry={nodes.Cone_Light4_HeadLight_0.geometry} material={materials.HeadLight} />
            </group>
            <group name="Cone_Light5" position={[15.226, 2.725, -2]} rotation={[0, 0, Math.PI / 2]} scale={[1, 8, 1]}>
              <mesh name="Cone_Light5_HeadLight_0" geometry={nodes.Cone_Light5_HeadLight_0.geometry} material={materials.HeadLight} />
            </group>
          </group>
          <group name="Buoy" position={[10, 1.853, -9]} rotation={[-0.048, -1.048, -0.019]}>
            <group name="Buoy_Base" position={[-18, -2, 11]}>
              <group name="Buoy_FrontX_2" position={[18, 1.9, -10.56]} rotation={[0, 0, -0.576]} scale={[0.1, 1.5, 0.1]}>
                <mesh name="Buoy_FrontX_2_Person_MAT_0" geometry={nodes.Buoy_FrontX_2_Person_MAT_0.geometry} material={materials.PaletteMaterial003} />
              </group>
              <group name="Buoy_FrontX_1" position={[18, 1.9, -10.56]} rotation={[0, 0, 0.576]} scale={[0.1, 1.5, 0.1]}>
                <mesh name="Buoy_FrontX_1_Person_MAT_0" geometry={nodes.Buoy_FrontX_1_Person_MAT_0.geometry} material={materials.PaletteMaterial003} />
              </group>
              <group name="Buoy_SideX2" position={[17.56, 1.9, -11]} rotation={[0, Math.PI / 2, 0]}>
                <mesh name="Buoy_SideX2_Person_MAT_0" geometry={nodes.Buoy_SideX2_Person_MAT_0.geometry} material={materials.PaletteMaterial003} />
              </group>
              <group name="Buoy_SideX1" position={[18.44, 1.9, -11]} rotation={[0, Math.PI / 2, 0]}>
                <mesh name="Buoy_SideX1_Person_MAT_0" geometry={nodes.Buoy_SideX1_Person_MAT_0.geometry} material={materials.PaletteMaterial003} />
              </group>
              <group name="Buoy_BackX_2" position={[18, 1.9, -11.44]} rotation={[0, 0, -0.576]} scale={[0.1, 1.5, 0.1]}>
                <mesh name="Buoy_BackX_2_Person_MAT_0" geometry={nodes.Buoy_BackX_2_Person_MAT_0.geometry} material={materials.PaletteMaterial003} />
              </group>
              <group name="Buoy_BackX_1" position={[18, 1.9, -11.44]} rotation={[0, 0, 0.576]} scale={[0.1, 1.5, 0.1]}>
                <mesh name="Buoy_BackX_1_Person_MAT_0" geometry={nodes.Buoy_BackX_1_Person_MAT_0.geometry} material={materials.PaletteMaterial003} />
              </group>
              <group name="Buoy_Leg4" position={[17.55, 2.25, -11.45]} scale={[0.1, 2.5, 0.1]}>
                <mesh name="Buoy_Leg4_Person_MAT_0" geometry={nodes.Buoy_Leg4_Person_MAT_0.geometry} material={materials.PaletteMaterial003} />
              </group>
              <group name="Buoy_Leg3" position={[18.45, 2.25, -11.443]} scale={[0.1, 2.5, 0.1]}>
                <mesh name="Buoy_Leg3_Person_MAT_0" geometry={nodes.Buoy_Leg3_Person_MAT_0.geometry} material={materials.PaletteMaterial003} />
              </group>
              <group name="Buoy_Leg2" position={[18.45, 2.25, -10.55]} scale={[0.1, 2.5, 0.1]}>
                <mesh name="Buoy_Leg2_Person_MAT_0" geometry={nodes.Buoy_Leg2_Person_MAT_0.geometry} material={materials.PaletteMaterial003} />
              </group>
              <group name="Buoy_Leg1" position={[17.55, 2.25, -10.55]} scale={[0.1, 2.5, 0.1]}>
                <mesh name="Buoy_Leg1_Person_MAT_0" geometry={nodes.Buoy_Leg1_Person_MAT_0.geometry} material={materials.PaletteMaterial003} />
              </group>
              <group name="Buoy_Bottom" position={[18, 0.75, -11]} scale={[1.5, 0.5, 1.5]}>
                <mesh name="Buoy_Bottom_Person_MAT_0" geometry={nodes.Buoy_Bottom_Person_MAT_0.geometry} material={materials.PaletteMaterial003} />
              </group>
              <group name="Buoy_Base1" position={[18, 1.3, -11]} scale={[1, 0.2, 1]}>
                <mesh name="Buoy_Base1_Person_MAT_0" geometry={nodes.Buoy_Base1_Person_MAT_0.geometry} material={materials.PaletteMaterial003} />
              </group>
              <group name="Buoy_Base2" position={[18, 2.8, -11]} scale={[1, 0.75, 1]}>
                <mesh name="Buoy_Base2_Person_MAT_0" geometry={nodes.Buoy_Base2_Person_MAT_0.geometry} material={materials.PaletteMaterial003} />
              </group>
              <group name="Buoy_Base3" position={[18, 3.5, -11]} scale={[1, 0.2, 1]}>
                <mesh name="Buoy_Base3_Person_MAT_0" geometry={nodes.Buoy_Base3_Person_MAT_0.geometry} material={materials.PaletteMaterial003} />
              </group>
            </group>
            <group name="Buoy_Supports" position={[-13, -2, 9]}>
              <group name="GreenLight_Support" position={[13, 5.5, -9]} scale={[0.2, 0.1, 0.2]}>
                <mesh name="GreenLight_Support_Metal_MAT_0" geometry={nodes.GreenLight_Support_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
              </group>
              <group name="GreenLight_Bracket" position={[14, 5.5, -9.1]} scale={[0.2, 0.2, 0.02]}>
                <mesh name="GreenLight_Bracket_Metal_MAT_0" geometry={nodes.GreenLight_Bracket_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
              </group>
              <group name="GreenLight_Back" position={[14, 5.2, -9.1]} scale={[0.4, 0.3, 0.02]}>
                <mesh name="GreenLight_Back_Ground_MAT_0" geometry={nodes.GreenLight_Back_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="RedLIght_Support" position={[13, 4.5, -9]} scale={[0.2, 0.1, 0.2]}>
                <mesh name="RedLIght_Support_Metal_MAT_0" geometry={nodes.RedLIght_Support_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
              </group>
              <group name="RedLight_Bracket" position={[14, 4.5, -9.1]} scale={[0.2, 0.2, 0.02]}>
                <mesh name="RedLight_Bracket_Metal_MAT_0" geometry={nodes.RedLight_Bracket_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
              </group>
              <group name="RedLight_Back" position={[14, 4.2, -9.1]} scale={[0.4, 0.3, 0.02]}>
                <mesh name="RedLight_Back_Ground_MAT_0" geometry={nodes.RedLight_Back_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Traffic_Pipe1" position={[13.502, 4.5, -9.334]}>
                <mesh name="Traffic_Pipe1_Metal_MAT_0" geometry={nodes.Traffic_Pipe1_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
              </group>
              <group name="Traffic_Pipe2" position={[13.502, 5.5, -9.334]}>
                <mesh name="Traffic_Pipe2_Metal_MAT_0" geometry={nodes.Traffic_Pipe2_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
              </group>
              <group name="Traffic_Pipe3" position={[12.502, 6, -9.334]}>
                <mesh name="Traffic_Pipe3_Metal_MAT_0" geometry={nodes.Traffic_Pipe3_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
              </group>
              <group name="Traffic_Pipe4" position={[13.5, 5, -9.5]} scale={[0.05, 0.5, 0.05]}>
                <mesh name="Traffic_Pipe4_Metal_MAT_0" geometry={nodes.Traffic_Pipe4_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
              </group>
              <group name="Speaker_Support" position={[13, 6, -9]} scale={[0.2, 0.1, 0.2]}>
                <mesh name="Speaker_Support_Metal_MAT_0" geometry={nodes.Speaker_Support_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
              </group>
            </group>
            <group name="Buoy_Traffic1" position={[1, 3.3, 0.08]} rotation={[Math.PI / 2, 0, 0]} scale={[0.4, 0.2, 0.4]}>
              <group name="GREEN_Light_CLOSE" position={[0, 0.725, 0]} scale={[1, 0.05, 1]}>
                <mesh name="GREEN_Light_CLOSE_Ground_MAT_0" geometry={nodes.GREEN_Light_CLOSE_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
              </group>
              <mesh name="Buoy_Traffic1_Ground_MAT_0" geometry={nodes.Buoy_Traffic1_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
              <mesh name="Buoy_Traffic1_GreenLight_0" geometry={nodes.Buoy_Traffic1_GreenLight_0.geometry} material={materials.PaletteMaterial005} />
            </group>
            <group name="Buoy_Traffic2" position={[1, 2.3, 0.08]} rotation={[Math.PI / 2, 0, 0]} scale={[0.4, 0.2, 0.4]}>
              <group name="RED_Light_CLOSE" position={[0, 0.725, 0]} scale={[1, 0.05, 1]}>
                <mesh name="RED_Light_CLOSE_Ground_MAT_0" geometry={nodes.RED_Light_CLOSE_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
              </group>
              <mesh name="Buoy_Traffic2_Ground_MAT_0" geometry={nodes.Buoy_Traffic2_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
              <mesh name="Buoy_Traffic2_RedLight_0" geometry={nodes.Buoy_Traffic2_RedLight_0.geometry} material={materials.PaletteMaterial006} />
            </group>
            <group name="Buoy_Sign" position={[0, 4.816, 0.2]} scale={[3, 1, 0.1]}>
              <mesh name="Buoy_Sign_Ground_MAT_0" geometry={nodes.Buoy_Sign_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="Buoy_Pole" position={[0, 2.5, 0]} scale={[0.15, 3.5, 0.15]}>
              <mesh name="Buoy_Pole_Metal_MAT_0" geometry={nodes.Buoy_Pole_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} />
            </group>
            <group name="Speaker" position={[-0.85, 3.88, 0.178]} rotation={[0.347, 0.374, 0.224]}>
              <mesh name="Speaker_Ground_MAT_0" geometry={nodes.Speaker_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} />
            </group>
          </group>
        </group>
        <mesh name="Ground_Ground_MAT_0" geometry={nodes.Ground_Ground_MAT_0.geometry} material={materials.PaletteMaterial001} position={[0, -0.047, 0]} scale={[1.868, 0.062, 1.557]} />
        <mesh name="Ground_Gravel_TX_0" geometry={nodes.Ground_Gravel_TX_0.geometry} material={materials.Gravel_TX} position={[0, -0.047, 0]} scale={[1.868, 0.062, 1.557]} />
        <mesh name="Ground_Seabed_TX_0" geometry={nodes.Ground_Seabed_TX_0.geometry} material={materials.Seabed_TX} position={[0, -0.047, 0]} scale={[1.868, 0.062, 1.557]} />
        <mesh name="Train_Track1_Wood_TX_0" geometry={nodes.Train_Track1_Wood_TX_0.geometry} material={materials.Wood_TX} position={[-0.428, -0.008, 0]} scale={[0.016, 0.003, 0.086]} />
        <mesh name="Train_Rail1_Rail_TX_0" geometry={nodes.Train_Rail1_Rail_TX_0.geometry} material={materials.Rail_TX} position={[0, -0.003, 0.023]} scale={[0.965, 0.006, 0.005]} />
        <mesh name="pCylinder71_Metal_MAT_0" geometry={nodes.pCylinder71_Metal_MAT_0.geometry} material={materials.PaletteMaterial003} position={[-0.54, 0.218, -0.523]} rotation={[0, 0.107, 0]} scale={[0, 0.006, 0]} />
        <mesh name="Station_Platform_Pristine_MAT_0" geometry={nodes.Station_Platform_Pristine_MAT_0.geometry} material={materials.Pristine_MAT} scale={0.016} />
        <mesh name="Station_Platform_Yellow_0" geometry={nodes.Station_Platform_Yellow_0.geometry} material={materials.Yellow} scale={0.016} />
        <mesh name="Seat1_Seat2_MAT1_0" geometry={nodes.Seat1_Seat2_MAT1_0.geometry} material={materials.Seat2_MAT1} position={[-0.21, 0, 0]} scale={0.016} />
        <mesh name="Seat2_Seat1_MAT_0" geometry={nodes.Seat2_Seat1_MAT_0.geometry} material={materials.Seat1_MAT} position={[-0.21, 0, 0]} scale={0.016} />
        <mesh name="LongLight_Pane_Glass_MAT_0" geometry={nodes.LongLight_Pane_Glass_MAT_0.geometry} material={materials.PaletteMaterial004} position={[-0.28, 0.125, -0.219]} scale={[0.056, 0.008, 0]} />
        <mesh name="Station_Sign_StationSign_0" geometry={nodes.Station_Sign_StationSign_0.geometry} material={materials.StationSign} position={[-0.28, 0.093, -0.214]} scale={[0.078, 0.047, 0.003]} />
        <mesh name="Cone_Light1_LampLight_0" geometry={nodes.Cone_Light1_LampLight_0.geometry} material={materials.LampLight} position={[-0.202, 0.1, 0.154]} scale={[0.016, 0.054, 0.016]} />
        <mesh name="Sign_CautionSign_0" geometry={nodes.Sign_CautionSign_0.geometry} material={materials.CautionSign} position={[0.262, 0.093, 0.097]} rotation={[0, 0, Math.PI / 2]} scale={[0.009, 0.001, 0.009]} />
        <mesh name="Umbrella_WoodTracks_MAT_0" geometry={nodes.Umbrella_WoodTracks_MAT_0.geometry} material={materials.WoodTracks_MAT} position={[0.026, 0.028, 0.002]} rotation={[0.238, -0.241, -0.463]} scale={0.016} />
        <mesh name="Station_Number_StationNumber_0" geometry={nodes.Station_Number_StationNumber_0.geometry} material={materials.StationNumber} scale={0.016} />
      </group>
    </group>
  )
}

useGLTF.preload('/station-train-transformed.glb')
